// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yxymdvixfjiruejjftxu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl4eW1kdml4ZmppcnVlampmdHh1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ3MTk0MDMsImV4cCI6MjA1MDI5NTQwM30.1gnBmgMth-kKoaKBn5FNftxZzQQR4x0aulbCiD6ImTw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);